apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-testing
  namespace: nginx-testing
spec:
  selector:
    matchLabels:
      app: nginx-testing
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-testing
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-testing
  namespace: nginx-testing
spec:
  selector:
    app: nginx-testing
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: nginx-testing
    protocol: TCP
    port: 8080
    targetPort: 80
---

apiVersion: "v1"
kind: "Secret"
metadata:
  name: "nginxsecret"
  namespace: "default"
type: kubernetes.io/tls
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRekNDQWl1Z0F3SUJBZ0lVUEg2bjZPbWFZQU1tcXNFNmFoeVNGeWNHV1BFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URVdNQlFHQTFVRUF3d05ibWRwYm5ndGRHVnpkR2x1WnpFWE1CVUdBMVVFQ2d3T2JtZHBlR2x1TFhSbApjM1JwYm1jd0hoY05NalF3TVRBNE1EYzBNVEkyV2hjTk1qVXdNVEEzTURjME1USTJXakF4TVJZd0ZBWURWUVFECkRBMXVaMmx1ZUMxMFpYTjBhVzVuTVJjd0ZRWURWUVFLREE1dVoybDRhVzR0ZEdWemRHbHVaekNDQVNJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG1hWVYxb3J2bUp6MXROb0crWlRTZjE0TlVVdzdGZgptdG9CY0h4Z0tJWUFaeXBqOUJ6ekxvaUVhK1hjZzlqUms1RHJRUEk5b0Y1N3NINWlvMk1TR0VNZStlNDlCQ01mCmtGWVpEeHFCcDVta2tFLzg0REN5QkdZYWYxWWVVS29ieTkrek1VZzA2U2pwL0RtWStFRW5RcW9OYlpJUkpRbnkKL3JCdTFOS0tONkRCYWdCV2tVSTBFeFdpcmVXRkRoaG1JMEg3NnZsZVZnYjF6NGJDbW1KMmRjdjJGbFhPUm81UgpHdEdYaUFWR1QvdGJNRzRzV3NnSEtDcjhPMWFLYlZDdTRCSTVPZEh0YWFtZUR3ZFR6QkNYY0JJbVFScHd6d2hYCkpoQW1kNXN1QjZ2UTFjL0FNM2RIZFFHUTVidS8rcWJLOXVmWjJCbGtuQ2RYOE5iRFJuYVhaZmtDQXdFQUFhTlQKTUZFd0hRWURWUjBPQkJZRUZIYmI3bFh2dWcrODlWM2RDcENySHI0R2xSUGRNQjhHQTFVZEl3UVlNQmFBRkhiYgo3bFh2dWcrODlWM2RDcENySHI0R2xSUGRNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0VCQUJjUURYY2kyOGFwT1ltUHVPbEgza3cwSUs3R3llU1hjeW1rZEx0akRXSm04N1R2ajdteGhNcEoKVnhQbjdJaE9BUlluTjkwbTJxNE5iS1YyYno3Y1ZNc2dpcjhqMHRsblY1cmNsSTQzdForMURjczhiNkhqR0c5TwpqUEk5Z2RWTkVpM3lpRi9LSXdaVWZmU2M2UGNLelZTQUwweitxQ2w2WkdhT0JKTWRld3VzTENIRWF1azF0NGVmClkySXJFSzltOEhBWDhZcXZYWnBNa1haaUpLQi9DTjdJUTh1RURVUERzK0tndVRwczdUbnEvUEdueXA5MURiN2sKVm1uK3lTcDBnUHlhNzk0dExxcm5LUGZONzViRmpXM2VxL3FlYnNtdkpSYTdEV0dEN3ZBQVFoY3lZRUsyTmlSMwplNGRHVnYyVU9Bc05Jc2JYRm5YejNuMzkrYkgrd2hnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQzVtbUZkYUs3NWljOWIKVGFCdm1VMG45ZURWRk1PeFg1cmFBWEI4WUNpR0FHY3FZL1FjOHk2SWhHdmwzSVBZMFpPUTYwRHlQYUJlZTdCKwpZcU5qRWhoREh2bnVQUVFqSDVCV0dROGFnYWVacEpCUC9PQXdzZ1JtR245V0hsQ3FHOHZmc3pGSU5Pa282Znc1Cm1QaEJKMEtxRFcyU0VTVUo4djZ3YnRUU2lqZWd3V29BVnBGQ05CTVZvcTNsaFE0WVppTkIrK3I1WGxZRzljK0cKd3BwaWRuWEw5aFpWemthT1VSclJsNGdGUmsvN1d6QnVMRnJJQnlncS9EdFdpbTFRcnVBU09UblI3V21wbmc4SApVOHdRbDNBU0prRWFjTThJVnlZUUpuZWJMZ2VyME5YUHdETjNSM1VCa09XN3YvcW15dmJuMmRnWlpKd25WL0RXCncwWjJsMlg1QWdNQkFBRUNnZ0VBRFVuNTBHNjFQNEh2M2pOT3lrckZTTmdNb09rUGtXaTlYVUJXNGRyZkwrZ0IKdXZuazRibENNczFiYmQzMTlUMWROZFk0UkZmbi9uZlg5VmFoNk84ajNGTndsTythdHhxVWtxdVE1cWFUbmRjMwo2M2c1UTVkTlpCT2YzQ1pIdzRSQnVzcTVXN2lKSExBektsc1M1RlJYckRZUnF6Q04wTHBzcEt5TTBhWEtrWmlFClk4WXVnUGJFZ3Naa2Z2b1Ivemg3dE5CQ1JnaC9IWjNUMmlOd1BQd0ovbzNDYzcxWDFsalp5MjRCSkN5UnFlNlIKdnNUYWxmWjZlcmowRFlhVW1pVENkQzFnc2pEb3FSOHpybHp1ZDJyQWZySU5NalB6L0MyRkR6ZFhoUkI4alhDdQpGN1NxVXFlanVqYWwrTEdadlY5cUoyQnozWVBVdnZWQVpyemk3OGFTY1FLQmdRRGJVOEd6Rnc0eTJYeDBlWXJVCkg3NXdPZXVnaU5hdHA3ekVNOFdvNDZjTGt0QWd0VnhaSTdaZ1Z0aUV1SGlxRmYyR3lLQ25xcGpKWGl1UGVqRDMKeElMUEkrWHJHOHdwSEZzQ1NvOTUwNnYvNGJGeldFZFIvRzRJSmNiNm1oUlVDU0JOWEJMWXpnb2pOZUhnbHhyMQp0YWI4TW1ubXNGbjRrbzFQZ1dBakp3SFVFUUtCZ1FEWW94STF5UXBYQUpsbjRJVTE5MHJRWENUaGtwc3h5WHRSCmpkTThGNUV6ZS9rYldJbDI0Y0NvY21WMFVXR2tRbHZIRXp1dnpBazMvaGNZZjJsdU1vek5wVXBIUi9zeGdaTG4KY2NRUWlHYUVFanE0ZEMrTU1VWlpFM3Jlb2JHM24wUmhMV2FwTDBZRG1vVjFWWEVKamE2cEpyUmd2QjBjMU1RZQpUWVd3cFArN2FRS0JnQno0dm1CNnppeFhZRUkrZitFdlpFZU16eHhBbHlNUFFqY2tvNXFBbitNK2ZIR2xvMUkvCkRtdEJiWTV5azdYYis4WmZJQ0dsdmxMek5vdllWem1UWXJnY0JOWCtzUVJKTTVoazR2anp4Z2VoOTMvR0RIMisKKzRYbC81ZkEzS2lSSUF3MyttRmJMaW1paDNqVVhRSlNBWUhVNHZwUEYwTm5rSFVOSVBiand6RVJBb0dBVkNQUgorTTNpbERRSllRMFU4QWJpS2RjQUJCU2E3bFZnN2lYMWV3dDBPOWpVd2NnN2E4NzJzdlhyYmFnR0VuUXJqVUJ0CkdEUlpDRVJKMkJ2MGFQWjlOWW9UTldoQnFkSzNxZWpIeTl3T1pSRm5lU2kzSnU0a2NvaGNXb2ZXcklqUldDVDQKRUpIcDBaQjhjVHdFTVQrMExNSjVvSEN2cGZrRlN2ZTFDd3lxdnJFQ2dZQmxPZVE2d0gxamxvbUpheWlZaTNDQQp0M2FVWm1JdVNLUzBTUVpCY00vM1EyQnV0Q3NBUlN5OUJucU44M3hTalhkejFoMTRObEtUS3RGQWVTanlRUUVtClJMckhWTlIvNzlTaWtoSU5SNFErdXp0eXZDdHhHdXBERU5MNHhxWUZ6TldaaGFLV1pNQkRqZlE5T3JBUTAwSk4KYUlyYWxFeDdJWW81OVZEaHlqMG4zdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
# ---

# # https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-testing
#   namespace: default
# spec:
#   rules:
#   - host: foo.bar.com
#     http:
#       paths:
#       - path: /
#         pathType: portal
#         backend:
#           service:
#             name: nginx-testing
#             port:
#               number: 8080

