apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-testing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /testing
        backend:
          service:
            name: my-app-testing
            port:
              number: 80